FROM node:lts as dependencies
WORKDIR /Client
EXPOSE 5173
COPY package.json ./
RUN npm install

FROM node:lts as builder
WORKDIR /Client
COPY . .
COPY --from=dependencies /Client/node_modules ./node_modules
RUN npm run build

FROM node:lts as runner
WORKDIR /Client
COPY --from=builder /Client/public ./public
COPY --from=builder /Client/dist ./dist
COPY --from=builder /Client/node_modules ./node_modules
COPY --from=builder /Client/package.json ./package.json
CMD ["npm", "run" , "start"]
